/** Lucide icon names for intelligence skills — stored as string key in skill JSON */
export const SKILL_ICON_OPTIONS: { name: string; label: string }[] = [
  { name: '', label: '无图标' },
  { name: 'ShieldCheck', label: '盾牌' },
  { name: 'Shield', label: '防护' },
  { name: 'ShieldAlert', label: '安全告警' },
  { name: 'Search', label: '搜索' },
  { name: 'FileSearch', label: '文件搜索' },
  { name: 'FolderSearch', label: '目录搜索' },
  { name: 'ScanSearch', label: '扫描搜索' },
  { name: 'UserSearch', label: '人员搜索' },
  { name: 'Database', label: '数据库' },
  { name: 'Server', label: '服务器' },
  { name: 'HardDrive', label: '存储' },
  { name: 'Newspaper', label: '新闻' },
  { name: 'Globe', label: '全球' },
  { name: 'MapPin', label: '地理' },
  { name: 'Radar', label: '雷达' },
  { name: 'Satellite', label: '卫星' },
  { name: 'Network', label: '网络' },
  { name: 'Link', label: '链接' },
  { name: 'Eye', label: '监视' },
  { name: 'Fingerprint', label: '指纹' },
  { name: 'Lock', label: '加密' },
  { name: 'Key', label: '密钥' },
  { name: 'Brain', label: '智能' },
  { name: 'Bot', label: '机器人' },
  { name: 'Sparkles', label: 'AI' },
  { name: 'Target', label: '目标' },
  { name: 'Crosshair', label: '定位' },
  { name: 'Users', label: '团队' },
  { name: 'Building', label: '企业' },
  { name: 'Briefcase', label: '商务' },
  { name: 'BookOpen', label: '知识' },
  { name: 'FileText', label: '文档' },
  { name: 'ClipboardList', label: '清单' },
  { name: 'Scan', label: '扫描' },
  { name: 'Microscope', label: '微观' },
  { name: 'Telescope', label: '远观' },
  { name: 'Bug', label: '漏洞' },
  { name: 'AlertTriangle', label: '警告' },
  { name: 'Zap', label: '快速' },
  { name: 'Flame', label: '热点' },
  { name: 'TrendingUp', label: '趋势' },
  { name: 'BarChart3', label: '柱状图' },
  { name: 'PieChart', label: '饼图' },
  { name: 'LineChart', label: '折线图' },
  { name: 'MessagesSquare', label: '对话' },
  { name: 'Mail', label: '邮件' },
  { name: 'Phone', label: '电话' },
  { name: 'Camera', label: '影像' },
  { name: 'Image', label: '图片' },
  { name: 'Video', label: '视频' },
  { name: 'Radio', label: '信号' },
  { name: 'Hash', label: '标签' },
  { name: 'Tag', label: '分类' },
  { name: 'Layers', label: '层级' },
  { name: 'Puzzle', label: '拼图' },
  { name: 'Settings', label: '设置' },
  { name: 'Wrench', label: '工具' },
]

export const SKILL_ICON_NAMES = new Set(
  SKILL_ICON_OPTIONS.filter((o) => o.name).map((o) => o.name)
)
