#!/usr/bin/env node
// Stage the static landing site into ./dist:
//   - root index.html (the slim landing)
//   - view/index.html (viewer-focused sub-page)
//   - build/index.html (builder-focused sub-page)
//   - styles.css (shared)
//   - scripts/site.js (shared client behaviour: theme toggle,
//     playground iframe overlay, screenshot lightbox)
//   - icon.svg (workspace asset)
//   - screenshots/*.png (sourced from apps/chrome-extension/store-assets)
// Matches the layout the GitHub Pages workflow publishes so a developer
// can preview locally before deploying.

import { copyFile, cp, mkdir, readdir, rm, stat } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import { verifyLinks } from "./scripts/verify-links.mjs";

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = join(here, "..", "..");
const dist = join(here, "dist");

await rm(dist, { recursive: true, force: true });
await mkdir(join(dist, "screenshots"), { recursive: true });
await mkdir(join(dist, "scripts"), { recursive: true });
await mkdir(join(dist, "view"), { recursive: true });
await mkdir(join(dist, "build"), { recursive: true });

await copyFile(join(here, "index.html"), join(dist, "index.html"));
await copyFile(
  join(here, "view", "index.html"),
  join(dist, "view", "index.html"),
);
await copyFile(
  join(here, "build", "index.html"),
  join(dist, "build", "index.html"),
);

// Reference HTML — generated by @slideglance/builder codegen. Copy the
// pre-built tree into dist/build/reference/. If the directory is missing,
// the build still succeeds but the deep-links from build/index.html will 404.
const referenceSrc = join(repoRoot, "packages", "builder", "reference-html");
try {
  await cp(referenceSrc, join(dist, "build", "reference"), {
    recursive: true,
  });
} catch {
  console.warn(
    `[landing] reference-html not found at ${referenceSrc} — ` +
      `run \`pnpm --filter @slideglance/builder run codegen\` first.`,
  );
}

await copyFile(join(here, "styles.css"), join(dist, "styles.css"));
await copyFile(
  join(here, "scripts", "site.js"),
  join(dist, "scripts", "site.js"),
);
await copyFile(
  join(repoRoot, "assets", "icon", "source.svg"),
  join(dist, "icon.svg"),
);

const shotDir = join(
  repoRoot,
  "apps",
  "chrome-extension",
  "store-assets",
  "screenshots",
);
const shots = (await readdir(shotDir)).filter((name) =>
  name.toLowerCase().endsWith(".png"),
);
for (const name of shots) {
  await copyFile(join(shotDir, name), join(dist, "screenshots", name));
}

// If the playground has already been built locally, mirror it under
// dist/playground/ so the overlay iframe has something to load when the
// user previews via `node serve.mjs`. The Pages workflow performs the
// equivalent copy in a separate step, so the local build is purely a
// developer-experience nicety.
const playgroundDist = join(repoRoot, "apps", "web-playground", "dist");
let playgroundFiles = 0;
try {
  const info = await stat(playgroundDist);
  if (info.isDirectory()) {
    await cp(playgroundDist, join(dist, "playground"), { recursive: true });
    playgroundFiles = (await readdir(join(dist, "playground"))).length;
  }
} catch {
  // Playground not built — overlay iframe will be empty until the
  // developer runs `pnpm --filter @slideglance/web-playground build`.
}

const playgroundNote =
  playgroundFiles > 0
    ? `, playground (${playgroundFiles} entries)`
    : ", no playground (run web-playground build for the overlay)";
console.log(
  `[landing] built -> ${dist} (${shots.length} screenshots, 1 icon${playgroundNote})`,
);

// Post-build link verification — catches deep-links to non-existent
// reference pages (e.g. when builder codegen was not run before this build).
const failures = await verifyLinks(dist);
if (failures.length > 0) {
  console.error(`[landing] ${failures.length} broken relative link(s):`);
  for (const f of failures) {
    console.error(`  ${f.from} -> ${f.href} (expected ${f.resolved})`);
  }
  process.exit(1);
}
